[functions.api]
verify_jwt = false

[functions.fulfill-orders]
verify_jwt = false

[functions.fulfill-xcel-orders]
verify_jwt = false

[functions.verify-numbers]
verify_jwt = false

[functions.sync-provider-status]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
